
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karla
 */
public class InitView extends javax.swing.JFrame {

	boolean listoMovie = false;
	String movieName = "", movieFunc = "",  movieSala = ""; int movieEntradas = 0; 
	ImageIcon currentImg; boolean listo = false; String currentMovie;
	
	ArrayList<String> chairs = new ArrayList<>();
	
	ArrayList<String> reservasNames = new ArrayList<>();
	ArrayList<Integer> reservasNum = new ArrayList<>();
	
	
	/**
	 * Creates new form InitView
	 */
	public InitView() {
		initComponents();
		getContentPane().setBackground(Color.BLACK);
		if (listoMovie){
			cbMovie.setSelected(true);
//			moviePanel.setBackground(Color.PINK);
			moviePanLabel.setText(movieName);
		}
		reservasNames.add("matrix");
		reservasNames.add("ready player one");
		reservasNames.add("interstellar");
		reservasNames.add("the neon demon");
	}

	public InitView(String movieName, String movieFunc, String movieSala, int movieEntradas, ImageIcon currentImg,boolean listo) {
		initComponents();
		
		getValues( movieName, movieFunc, movieSala, movieEntradas, currentImg, listo);
		
	}
	public InitView(ArrayList<String> finalChairs,  String movieName) {
		initComponents();
		getValsChairs(finalChairs,  movieName);
	}
	
	public InitView(int paidValue) {
		initComponents();
		cbPay.setSelected(true);
		payPanLabel.setText("[ $ "+Integer.toString(paidValue)+" ]");
	}
	
	void getValues( String movieName1, String movieFunc1, String movieSala1, int movieEntradas1, ImageIcon currentImg1, boolean listo1){
		listoMovie = listo1;
		movieEntradas =  movieEntradas1;
		movieName = movieName1;
		movieFunc = movieFunc1;
		movieSala = movieSala1;
		currentImg = currentImg1;
		if (listo1){
			cbMovie.setSelected(true);
//			moviePanel.setBackground(Color.PINK);
			moviePanLabel.setText(movieName1);
		}
	}
//	debo recibir los valores relevantes de getvalues() porque sino pierdo el progreso
	void getValsChairs( ArrayList<String> finalChairs1, String movieName1){
		chairs = finalChairs1;
		movieName = movieName1;
		movieEntradas =  finalChairs1.size();
		if (!chairs.isEmpty())
			chairPanLabel.setText(chairs.toString());
			cbChairs.setSelected(true);
		cbMovie.setSelected(true);
//		moviePanel.setBackground(Color.PINK);
		moviePanLabel.setText(movieName1);
	}
	
	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        moviePanel = new javax.swing.JPanel();
        cbMovie = new javax.swing.JCheckBox();
        moviePanLabel = new javax.swing.JLabel();
        chairPanel = new javax.swing.JPanel();
        cbChairs = new javax.swing.JCheckBox();
        chairPanLabel = new javax.swing.JLabel();
        payPanel = new javax.swing.JPanel();
        cbPay = new javax.swing.JCheckBox();
        payPanLabel = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RESERVA DE TICKETS");

        moviePanel.setBackground(new java.awt.Color(102, 102, 102));
        moviePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moviePanelMouseClicked(evt);
            }
        });
        moviePanel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                moviePanelComponentShown(evt);
            }
        });

        cbMovie.setBackground(new java.awt.Color(102, 102, 102));
        cbMovie.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbMovie.setForeground(new java.awt.Color(255, 255, 255));
        cbMovie.setText("Pelicula");
        cbMovie.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cbMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMovieActionPerformed(evt);
            }
        });

        moviePanLabel.setForeground(new java.awt.Color(255, 255, 255));
        moviePanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        moviePanLabel.setText("[ Eliga una ]");

        javax.swing.GroupLayout moviePanelLayout = new javax.swing.GroupLayout(moviePanel);
        moviePanel.setLayout(moviePanelLayout);
        moviePanelLayout.setHorizontalGroup(
            moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moviePanelLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(cbMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
            .addComponent(moviePanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        moviePanelLayout.setVerticalGroup(
            moviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(moviePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbMovie)
                .addGap(50, 50, 50)
                .addComponent(moviePanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        chairPanel.setBackground(new java.awt.Color(102, 102, 102));
        chairPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chairPanelMouseClicked(evt);
            }
        });

        cbChairs.setBackground(new java.awt.Color(102, 102, 102));
        cbChairs.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbChairs.setForeground(new java.awt.Color(255, 255, 255));
        cbChairs.setText("Sala/Asientos");
        cbChairs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChairsActionPerformed(evt);
            }
        });

        chairPanLabel.setForeground(new java.awt.Color(255, 255, 255));
        chairPanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        chairPanLabel.setText("[ Elergirlos ]");
        chairPanLabel.setToolTipText("");

        javax.swing.GroupLayout chairPanelLayout = new javax.swing.GroupLayout(chairPanel);
        chairPanel.setLayout(chairPanelLayout);
        chairPanelLayout.setHorizontalGroup(
            chairPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chairPanelLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(cbChairs)
                .addGap(17, 17, 17))
            .addComponent(chairPanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        chairPanelLayout.setVerticalGroup(
            chairPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(chairPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbChairs)
                .addGap(54, 54, 54)
                .addComponent(chairPanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        payPanel.setBackground(new java.awt.Color(102, 102, 102));
        payPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                payPanelMouseClicked(evt);
            }
        });

        cbPay.setBackground(new java.awt.Color(102, 102, 102));
        cbPay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        cbPay.setForeground(new java.awt.Color(255, 255, 255));
        cbPay.setText("Pago");

        payPanLabel.setForeground(new java.awt.Color(255, 255, 255));
        payPanLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        payPanLabel.setText("[ Eliga un metodo ]");

        javax.swing.GroupLayout payPanelLayout = new javax.swing.GroupLayout(payPanel);
        payPanel.setLayout(payPanelLayout);
        payPanelLayout.setHorizontalGroup(
            payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payPanelLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(cbPay, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
            .addComponent(payPanLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        payPanelLayout.setVerticalGroup(
            payPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(payPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbPay)
                .addGap(51, 51, 51)
                .addComponent(payPanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Reservar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(moviePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chairPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(payPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(moviePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chairPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(payPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMovieActionPerformed
       
    }//GEN-LAST:event_cbMovieActionPerformed

    private void cbChairsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChairsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChairsActionPerformed

    private void moviePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moviePanelMouseClicked
       MovieFrame movFr = new MovieFrame();
	   movFr.setVisible(true);
	   this.setVisible(false);
	   this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
	   this.dispose();
	   
    }//GEN-LAST:event_moviePanelMouseClicked

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
//       aja

		   
    }//GEN-LAST:event_formComponentShown

    private void moviePanelComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_moviePanelComponentShown
       
    }//GEN-LAST:event_moviePanelComponentShown

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
       if (listo)
		JOptionPane.showMessageDialog(rootPane,movieName, movieSala, HEIGHT, currentImg);
	
    }//GEN-LAST:event_formWindowActivated

    private void chairPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chairPanelMouseClicked
       
	if (listoMovie){
		ChairsFrame chairsFr = new ChairsFrame(movieEntradas,  movieName);
		chairsFr.setVisible(true);
		this.setVisible(false);
		this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
		this.dispose();
	}else
		JOptionPane.showMessageDialog(null,"Debe elegir primero una pelicula haciendo click en la tarjeta de pelicula", "Pelicula No Elegida", JOptionPane.ERROR_MESSAGE);
	
    }//GEN-LAST:event_chairPanelMouseClicked

    private void payPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_payPanelMouseClicked
	System.out.println(movieEntradas);
	new  PayFrame(movieName,movieEntradas).setVisible(true);
	this.setVisible(false);
	this.setDefaultCloseOperation(this.EXIT_ON_CLOSE);
	this.dispose();
	   
    }//GEN-LAST:event_payPanelMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
	int num = reservasNum.get(0);
	if (movieName.contentEquals("matrix")){
		num = reservasNum.get(0);
		 reservasNum.add(num++); 
	}else if (movieName.contentEquals("ready player one")){
		num = reservasNum.get(1);
		reservasNum.add(num++); 
	}else if (movieName.contentEquals("interstellar")){
		num = reservasNum.get(2);
		reservasNum.add(num++); 
	}else if (movieName.contentEquals("the neon demon")){
		num = reservasNum.get(3);
		reservasNum.add(num++); 
	}
		 
    }//GEN-LAST:event_jButton1ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(InitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(InitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(InitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(InitView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new InitView().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbChairs;
    private javax.swing.JCheckBox cbMovie;
    private javax.swing.JCheckBox cbPay;
    private javax.swing.JLabel chairPanLabel;
    private javax.swing.JPanel chairPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel moviePanLabel;
    private javax.swing.JPanel moviePanel;
    private javax.swing.JLabel payPanLabel;
    private javax.swing.JPanel payPanel;
    // End of variables declaration//GEN-END:variables
}
